
# 在記憶體中最多儲存的訊息數量
MAX_MESSAGES = 256

# 每 5 秒檢查一次批踢踢信箱
CHECK_PTT_MAIL_INTERVAL = 5

# 每 10 秒檢查一次水球
CHECK_WATERBALL_INTERVAL = 10

# 每 120 秒檢查一次聯絡人在線狀態
CHECK_ONLINE_STATUS_INTERVAL = 120

# 當前開啟的對話視窗，每 10 秒檢查該使用者在線狀態
CHECK_ACTIVE_CHAT_ONLINE_INTERVAL = 10

# 在線狀態批次查詢時，每位使用者間隔 5 秒
ONLINE_CHECK_PER_USER_DELAY = 5

SERVICE_PORT = 53081